AWSTemplateFormatVersion: '2010-09-09'
Description: 'Staging Agent Monitoring Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: staging
    Description: Deployment environment
    
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type
    
  KeyPairName:
    Type: String
    Default: niro-agent-keypair
    Description: EC2 Key Pair name

Resources:
  MonitoringVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: staging-monitoring-vpc

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MonitoringVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: staging-monitoring-subnet

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: staging-monitoring-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MonitoringVPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MonitoringVPC
      Tags:
        - Key: Name
          Value: staging-monitoring-rt

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for agent monitoring
      VpcId: !Ref MonitoringVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 7778
          ToPort: 7778
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8090
          ToPort: 8090
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: staging-monitoring-sg

  MonitoringInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a19bcec6d2ec60fb
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: staging-agent-monitor

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref MonitoringVPC
    
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MonitoringInstance
    
  PublicIP:
    Description: Public IP address
    Value: !GetAtt MonitoringInstance.PublicIp
    
  SSHCommand:
    Description: SSH command to connect
    Value: !Sub 'ssh -i ~/.ssh/${KeyPairName}.pem ec2-user@${MonitoringInstance.PublicIp}'